[package]
name = "amun-network"
version = "1.0.0"
edition = "2021"
description = "Peer-to-peer network layer for AmunChain"

[dependencies]
amun-kernel-types = { path = "../amun-kernel-types" }
amun-failure = { path = "../amun-failure" }
amun-bls = { path = "../amun-bls" }
heapless = "0.8"
hashbrown = "0.14"
