[package]
license = "Apache-2.0"
name = "amun-defi-stress"
version = "0.1.0"
edition = "2021"
[dependencies]
amun-resource-core = { path = "../amun-resource-core" }
amun-defi-core = { path = "../amun-defi-core" }
amun-defi-amm = { path = "../amun-defi-amm" }
amun-defi-lending-core = { path = "../amun-defi-lending-core" }
amun-defi-lending-engine = { path = "../amun-defi-lending-engine" }
amun-defi-stablecoin = { path = "../amun-defi-stablecoin" }
amun-nft-collateral = { path = "../amun-nft-collateral" }
amun-nft-core = { path = "../amun-nft-core" }
sha2 = "0.11"
hex = "0.4"
rand = "0.8"
