[package]
name = "amun-protocol-event"
version = "1.0.0"
license = "MIT OR Apache-2.0"
edition = "2021"
description = "AmunChain canonical protocol events"

[dependencies]
amun-chain-position = { path = "../amun-chain-position" }
amun-binary-codec = { path = "../amun-binary-codec" }
blake3 = { version = "1.5", default-features = false }
