use serde::{Deserialize, Serialize};

/// Severity of an alert.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AlertSeverity {
    Info,
    Warning,
    Critical,
}

/// An alert generated by the health supervisor.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Alert {
    pub timestamp: u64,
    pub severity: AlertSeverity,
    pub component: String,
    pub message: String,
    pub action: String,
}

impl Alert {
    pub fn new(
        severity: AlertSeverity,
        component: impl Into<String>,
        message: impl Into<String>,
        action: impl Into<String>,
    ) -> Self {
        Self {
            timestamp: chrono::Utc::now().timestamp() as u64,
            severity,
            component: component.into(),
            message: message.into(),
            action: action.into(),
        }
    }

    pub fn validator_down(name: &str) -> Self {
        Self::new(
            AlertSeverity::Critical,
            name,
            format!("Validator {} is down", name),
            "Restarting with auto-recovery",
        )
    }

    pub fn service_degraded(service: &str) -> Self {
        Self::new(
            AlertSeverity::Warning,
            service,
            format!("Service {} is degraded", service),
            "Monitoring — will restart if persistent",
        )
    }

    pub fn quorum_lost() -> Self {
        Self::new(
            AlertSeverity::Critical,
            "network",
            "Quorum lost — network may be partitioned",
            "Manual intervention may be required",
        )
    }

    pub fn recovery_success(component: &str) -> Self {
        Self::new(
            AlertSeverity::Info,
            component,
            format!("{} recovered successfully", component),
            "No action needed",
        )
    }
}
