[package]
name = "amun-unlock-law"
version = "1.0.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
amun-quorum-certificate = { path = "../amun-quorum-certificate" }
amun-consensus-messages = { path = "../amun-consensus-messages" }
amun-validator-attestation = { path = "../amun-validator-attestation" }
amun-chain-position = { path = "../amun-chain-position" }
