[package]
name = "amun-replay-engine"
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = ["amun-constitutional/std"]

[dependencies]
amun-constitutional = { path = "../amun-constitutional", default-features = false }
sha2 = { version = "0.10", default-features = false }
