[package]
name = "amun-consensus-reactor"
version = "1.0.0"
license = "MIT OR Apache-2.0"
edition = "2021"
description = "AmunChain consensus event reactor"

[dependencies]
amun-chain-position = { path = "../amun-chain-position" }
amun-pacemaker = { path = "../amun-pacemaker" }
amun-view-change = { path = "../amun-view-change" }
amun-epoch-transition = { path = "../amun-epoch-transition" }
amun-deterministic-scheduler = { path = "../amun-deterministic-scheduler" }
amun-deterministic-timer = { path = "../amun-deterministic-timer" }
