[package]
name = "amun-contract-fuzzing"
version = "0.1.0"
edition = "2021"
[dependencies]
amun-resource-core = { path = "../amun-resource-core" }
amun-bytecode = { path = "../amun-bytecode" }
amun-contract-integration = { path = "../amun-contract-integration" }
amun-contract-registry = { path = "../amun-contract-registry" }
amun-gas-engine = { path = "../amun-gas-engine" }
sha2 = "0.11"
rand = "0.8"
