[package]
name = "amun-network-simulator"
version = "1.0.0"
license = "MIT OR Apache-2.0"
edition = "2021"
description = "AmunChain deterministic network delivery simulator"

[dependencies]
amun-chain-position = { path = "../amun-chain-position" }
amun-deterministic-timer = { path = "../amun-deterministic-timer" }
rand = "0.8"
