[package]
license = "Apache-2.0"
name = "amun-nft-collateral"
version = "0.1.0"
edition = "2021"
[dependencies]
amun-resource-core = { path = "../amun-resource-core" }
amun-nft-core = { path = "../amun-nft-core" }
amun-defi-lending-core = { path = "../amun-defi-lending-core" }
amun-defi-lending-engine = { path = "../amun-defi-lending-engine" }
sha2 = "0.11"
hex = "0.4"
