[package]
name = "amun-audit"
license = "MIT OR Apache-2.0"
version = "1.0.0"
edition = "2021"

[dev-dependencies]
amun-storage-kernel = { path = "../amun-storage-kernel" }
amun-snapshot-engine = { path = "../amun-snapshot-engine" }
amun-canonical-codec = { path = "../amun-canonical-codec" }
rand = "0.8"
rand_chacha = "0.3"
blake3 = "1.5"
tempfile = "3.8"
