[package]
license = "Apache-2.0"
name = "examples"
version = "0.1.0"
edition = "2021"
publish = false

[[example]]
name = "test_state_machine"
path = "test_state_machine.rs"

[dependencies]
amun_consensus_math = { path = "../crates/amun_consensus_math" }
amun_state_machine = { path = "../crates/amun_state_machine" }
