[package]
name = "amun-networking"
license = "MIT OR Apache-2.0"
version = "1.0.0"
edition = "2021"

[dependencies]
amun-canonical-codec = { path = "../amun-canonical-codec" }
amun-storage-kernel = { path = "../amun-storage-kernel" }
amun-snapshot-engine = { path = "../amun-snapshot-engine" }
amun-civilizational-relations = { path = "../amun-civilizational-relations" }
amun-constitutional-quarantine = { path = "../amun-constitutional-quarantine" }
blake3 = "1.5"
