[package]
license = "MIT OR Apache-2.0"
name = "amun-economic-service"
version = "0.1.0"
edition = "2021"

[dependencies]
amun-tokenomics = { path = "../amun-tokenomics" }
amun-tokenomics-ledger = { path = "../amun-tokenomics-ledger" }
serde_json = "1.0"
tiny_http = "0.12"
hex = "0.4"
ureq = "2.10"
