[package]
license = "MIT OR Apache-2.0"
name = "amun-nft-explorer"
version = "0.1.0"
edition = "2021"

[dependencies]
amun-resource-core = { path = "../amun-resource-core" }
amun-nft-core = { path = "../amun-nft-core" }
amun-nft-mining = { path = "../amun-nft-mining" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.11"
hex = "0.4"
