[package]
name = "amun-staking"
version = "1.0.0"
license = "MIT OR Apache-2.0"
edition = "2021"
description = "AmunChain staking module"
[dependencies]
amun-kernel-types = { path = "../amun-kernel-types" }
amun-failure = { path = "../amun-failure" }
amun-economics = { path = "../amun-economics" }
heapless = "0.8"
amun-validator-registry = { path = "../amun-validator-registry" }
