[package]
name = "amun-transaction"
version = "1.0.0"
license = "MIT OR Apache-2.0"
edition = "2021"
description = "Constitutional transaction format"

[dependencies]
amun-failure = { path = "../amun-failure" }
amun-kernel-types = { path = "../amun-kernel-types" }
amun-codec = { path = "../amun-codec" }
amun-constitution = { path = "../amun-constitution" }
heapless = "0.8"
