[package]
name = "amun-mempool-gossip"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Mempool with transaction gossip protocol"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_bytes = "0.11"
postcard = { version = "1", features = ["use-std"] }
blake3 = "1"
