[package]
name = "amun-consensus-types"
version = "1.0.0"
edition = "2021"
description = "Canonical consensus types"

[dependencies]
amun-failure = { path = "../amun-failure" }
amun-kernel-types = { path = "../amun-kernel-types" }
amun-codec = { path = "../amun-codec" }
amun-state-types = { path = "../amun-state-types" }
heapless = "0.8"
