[package]
license = "Apache-2.0"
name = "amun-accounts"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3 = "1.5"
amun-constitutional-commitment = { path = "../amun-constitutional-commitment" }
amun-tokenomics-ledger = { path = "../amun-tokenomics-ledger" }
amun-snapshot-engine = { path = "../amun-snapshot-engine" }
